Fix: Freeze anyio
If anyio moves to 4.0.0, the test suite
test_calculation_endpoints.py fails with error
AttributeError: module 'anyio' has no attribute 'start_blocking_portal'